config/routes.rb
Rails.application.routes.draw do

  if SingleUserMode.enabled?
    devise_for :users, skip: :registrations
  else
    devise_for :users
  end

  resource :dashboard, controller: "dashboard"
  resources :items do
    resources :links
  end

  root to: redirect('/dashboard')

  get "/:label" => "labels#show", as: "label_link"

end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  url        :string
#  user_id    :integer
#

class Item < ActiveRecord::Base
  belongs_to :user

  has_many :links

  validates_presence_of :url, :user
end

app/models/label_maker.rb
class LabelMaker

  def generate_short_label(index:, salt_count: 0)
    salts = salt_count.times.map { Packer.generate_single_segment_salt }
    data = [index] + salts

    Packer.pack(data)
  end

end

app/models/link.rb
# == Schema Information
#
# Table name: links
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  label      :string
#  item_id    :integer
#  label_type :string
#

class Link < ActiveRecord::Base
  LABEL_TYPES = %w(short guid custom)

  belongs_to :item

  validates :label, presence: true, uniqueness: true
  validates :label_type, inclusion: {in: LABEL_TYPES}

  attr_accessor :short_id, :salt_count

  def url(options = {})
    options[:label] = label

    Rails.application.routes.url_helpers.label_link_url(options)
  end

  def self.build_short_link
    salt_count = 1
    short_id = ShortLabelSequence.next
    label = LabelMaker.new.generate_short_label(salt_count: salt_count, index: short_id)

    new(label_type: "short", label: label, salt_count: salt_count, short_id: short_id)
  end

end

app/models/packer.rb
class Packer
  TWO_CHAR_UPPER_BOUND = 43 # Numbers higher than this require one more character

  class << self
    delegate :pack, :unpack, :generate_single_segment_salt, to: :instance
  end

  def pack(data)
    hashids.encode(data)
  end

  def unpack(data)
    hashids.decode(data)
  end

  def generate_single_segment_salt
    Random.rand(TWO_CHAR_UPPER_BOUND + 1)
  end

private

  def self.instance
    Packer.new
  end

  def hashids
    Hashids.new
  end

end

app/models/settings.rb
# == Schema Information
#
# Table name: settings
#
#  id         :integer          not null, primary key
#  var        :string           not null
#  value      :text
#  thing_id   :integer
#  thing_type :string(30)
#  created_at :datetime
#  updated_at :datetime
#

class Settings < RailsSettings::CachedSettings
end

app/models/short_label_sequence.rb
class ShortLabelSequence

  def self.next
    result = ActiveRecord::Base.connection.execute("SELECT nextval('short_link_seq')")

    result[0]["nextval"].to_i
  end

end

app/models/short_link_sequence.rb
class ShortLinkSequence

  def self.next
    result = ActiveRecord::Base.connection.execute("SELECT nextval('short_link_seq')")

    result[0]["nextval"].to_i
  end

end

app/models/single_user_mode.rb
class SingleUserMode

  def self.enabled?
    true
  end

  def self.master_user
    User.find_by!(master: true)

  rescue ActiveRecord::RecordNotFound
    create_master_user!
    retry
  end

  def self.create_master_user!
    User.transaction do
      our_master_user = User.create(master: true)

      ensure_only_one_master_or_rollback!(our_master_user)
    end
  end

private

  def self.ensure_only_one_master_or_rollback!(our_master_user)
    if User.where(master: true).many?
      first_master_user = User.where(master: true).order(created_at: "ASC").first

      if first_master_user != our_master_user
        raise ActiveRecord::Rollback, "There can be only one (master user)"
      end
    end
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime
#  updated_at             :datetime
#  master                 :boolean          default(FALSE)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  if SingleUserMode.enabled?
    # In Single User mode Devise doesn't need an email for the strategy to become valid
    # nor does anyone need to register.
    devise :database_authenticatable,
      :recoverable, :rememberable, :trackable, :validatable, authentication_keys: {email: false}
  else
    devise :database_authenticatable,
      :recoverable, :rememberable, :trackable, :validatabled, :registerable
  end

  has_many :items

  validates_uniqueness_of :master, if: :master

  def valid_password?(maybe_password)
    if master
      Devise.secure_compare(maybe_password, Rails.application.secrets.master_password)
    else
      super
    end
  end

  def self.find_first_by_auth_conditions(*)
    if SingleUserMode.enabled?
      SingleUserMode.master_user
    else
      super
    end
  end

private

  def password_required?
    !master && super
  end

  def email_required?
    !master && super
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def show
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = current_user.items
  end

  def new
    @item = current_user.items.new
    @link = @item.links.build_short_link
  end

  def create
    @item = current_user.items.new(item_params)
    @link = @item.links.new(link_params)

    if @item.save
      redirect_to items_path
    else
      render :new
    end
  end

private

  def item_params
    params.require(:item).permit(:url)
  end

  def link_params
    params.require(:link).permit(:label, :short_id, :salt_count)
  end

end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  skip_before_action :authenticate_user!

  def show
    redirect_to item.url
  end

private

  def item
    link.item
  end

  def link
    label = params[:label]

    Link.find_by(label: label)
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_item

  def new
    @link = @item.links.build_short_link
  end

  def create
    @link = @item.links.build(link_params)

    if @link.save
      redirect_to items_path
    else
      render :new
    end
  end

private

  def set_item
    @item = Item.find(params[:item_id])
  end

  def link_params
    params.require(:link).permit(:label, :short_id, :salt_count)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/labels_helper.rb
module LabelsHelper

  def label_path(link)
    label_link_path(label: link.label)
  end

  def label_url(link)
    label_link_url(label: link.label)
  end

end

app/views/dashboard/index.html.haml
Sign out

app/views/dashboard/show.html.haml
.container
  .row
    %h1
      Hi!
    %p.lead
      Wooooow

app/views/items/index.html.haml
.container
  - if @items.any?
    .row
      List of items

    - @items.each do |item|
      .row
        %h2
          = item.url
        %ul
          - item.links.each do |link|
            %li
              = link_to label_url(link) do
                = label_url(link)

          %li
            = link_to new_item_link_path(item) do
              Add New
  - else
    .row
      No items available

app/views/items/new.html.haml
%h2 Create a new link

- if @item.errors.any?
  %p
    Something went wrong:
    %ul
      - @item.errors.messages.each do |field, errors|
        %li
          = field
          = errors.to_sentence

%p
  = form_for @item do |form|
    %p
      = form.label :url, "Full URL:"
      = form.text_field :url

    %p
      = fields_for @link do |link_form|
        = link_form.label :label, "http://hellolocker.com/"
        = link_form.text_field :label

    = form.submit "Create"

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-fixed-top.navbar-dark.bg-inverse
  = link_to "Hello Locker", root_url, class: "navbar-brand"

  %ul.nav.nav-pills
    %li.nav-item.active
      = link_to new_item_path, class: "nav-link" do
        New Item
        %span.sr-only (current)

    %li.nav-item
      = link_to "About", "#", class: "nav-link"

    %li.nav-item
      = link_to "Contact", "#", class: "nav-link"

  %ul.nav.nav-pills.pull-right
    - if signed_in?
      %li.nav-item
        = link_to t(".sign_out"), destroy_user_session_path, method: "DELETE", class: "nav-link"

    - else
      %li.nav-item
        = link_to t(".sign_in"), new_user_session_path, class: "nav-link"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta(charset="utf-8")
    %meta(content="IE=edge" http-equiv="X-UA-Compatible")
    %meta(content="width=device-width, initial-scale=1" name="viewport")

    %title Hellolocker

    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    = render "layouts/navigation"
    = yield

app/views/links/new.html.haml
= form_for [@item, @link] do |form|
  = form.label :label, "http://hellolocker.com/"
  = form.text_field :label
  = form.submit "Create"